title: Test Resume of Nicholas Denny
author: Nicholas Denny
email: nicholas.denny@sbcglobal.net
description: > # this means to ignore newlines until "baseurl:"
  A site where Nicholas Denny can practice his online resume/portfolio
  creating in peace...

# social links
twitter_username: your-twitter-handle
github_username:  nimide

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
